---

- hosts: edge01-nicholas

  connection: network_cli
  gather_facts: 'no'

  tasks:
    - name: Configure remote edge01-nicholas
      vyos_config:
        lines:
          - set system host-name edge01-nicholas
          - set system name-server 203.0.113.254
          - set service ssh disable-host-validation
          - set system login user vyos authentication public-keys docker@work type ssh-rsa
          - set system login user vyos authentication public-keys docker@work key "{{ lookup('file', 'id_rsa_docker.pub') }}"
          - set interfaces ethernet eth0 description WAN
          - set interfaces ethernet eth1 description LAN
          - set interfaces ethernet eth2 description DMZ
          
